name: CI/CD SanityTest Pipeline
on:
  workflow_dispatch:

jobs:
  Server_Config:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’» Checkout Repo
        uses: actions/checkout@v4

      - name: ğŸ—„ï¸ Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: ğŸ™ Install Dependencies
        run: npm install

      - name: ğŸ“¦ Upload Cypress Structure
        uses: actions/upload-artifact@v2
        with:
          name: cypress-structure
          path: cypress/**  # Sube toda la carpeta cypress y su contenido

  SanityTest:
    runs-on: ubuntu-latest
    needs: Server_Config
    steps:
      - name: ğŸ“¥ Download Cypress Structure
        uses: actions/download-artifact@v2
        with:
          name: cypress-structure

      - name: ğŸ—„ï¸ Restore Node Modules Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: ğŸ§ª Run Sanity Test
        run: |
          # AquÃ­ puedes acceder a la carpeta cypress y ejecutar las pruebas
          npx cypress run
